version: '3'

services:
  app:
    container_name: ts-node-app
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file:
      - .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend

networks:
  backend:
    driver: bridge
